easylab/urls.py
from django.contrib import admin
from django.urls import include, path

from users import views

urlpatterns = [
    path('labs/', include('labs.urls')),
    path('admin/', admin.site.urls),
    path("register-student/", views.register_request_student, name="register_student"),
    path("register-teacher/", views.register_request_teacher, name="register_teacher"),
    path("login/", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),

]

labs/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = 'labs'

urlpatterns = [
    path('', views.index, name='index'),
    # ex: /labs/5/
    path('<int:laboratory_id>/', views.detail, name='detail'),
    # ex: /labs/5/send/
    path('<int:laboratory_id>', views.detail, name='send'),
    path('new_lab/', views.new_lab, name='new_lab')
]

labs/models.py
from django.db import models

from users.models import Subject


class Laboratory(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE
                                )  # 1 subject -> * laboratory


class Language(models.Model):
    title = models.CharField(max_length=30, primary_key=True)
    description = models.CharField(max_length=30)  # Title that user see


class TestCase(models.Model):
    laboratory = models.ForeignKey(
        Laboratory, on_delete=models.CASCADE
    )  # 1 laboratory -> * laboratory tests

    description = models.CharField(max_length=200)  # description about this test
    description_input = models.CharField(max_length=1000)  # example input
    description_output = models.CharField(max_length=1000)  # example output
    expected_output = models.CharField(max_length=1000)  # expected student output


class LaboratoryInLanguage(models.Model):
    laboratory = models.ForeignKey(
        Laboratory, on_delete=models.CASCADE
    )  # 1 laboratory -> * laboratory in language
    language = models.ForeignKey(
        Language, on_delete=models.CASCADE
    )  # 1 language -> * laboratory in language
    test_case = models.ForeignKey(
        TestCase, on_delete=models.CASCADE
    )  # 1 test_case -> * laboratory in language

    code = models.CharField(max_length=200)  # code that runs before user code

# class UserAnswer(models.Model):
#     laboratory = models.ForeignKey(Laboratory, on_delete=models.CASCADE)  # 1 laboratory -> * user answers
#     language = models.ForeignKey(Language, on_delete=models.CASCADE)  # 1 language -> * user answers
#     # TODO: user = models.ForeignKey(User, on_delete=models.CASCADE)  # user laboratory -> * user answers
#
#     code = models.CharField(max_length=5000)
#     upload_date = models.DateTimeField('date uploaded')

# python manage.py makemigrations labs
# python manage.py migrate
# python manage.py shell
# from labs.models import *
# from django.utils import timezone
# lab = Laboratory(title='Lab', description='descr', pub_date=timezone.now())
# lab.save()
# python = Language(title='python', description='Python')
# js = Language(title='js', description='JavaS')
# cpp = Language(title='cpp', description='C++')
# python.save()
# js.save()
# cpp.save()
# tc = TestCase(laboratory=lab, description='description2', description_input='case_input2', description_output='case_output2', expected_output='1')
# tc.save()
# lil_cpp = LaboratoryInLanguage(laboratory=lab, language=cpp, test_case=tc, code='string text="1";')
# lil_js = LaboratoryInLanguage(laboratory=lab, language=js, test_case=tc, code='text=1')
# lil_python = LaboratoryInLanguage(laboratory=lab, language=python, test_case=tc, code='text=1')
# lil_cpp.save()
# lil_python.save()
# lil_js.save()
# tc2 = TestCase(laboratory=lab, description='description_hello', description_input='hello', description_output='hello', expected_output='Hello world!')
# tc2.save()
# lil2_python = LaboratoryInLanguage(laboratory=lab, language=python, test_case=tc, code='text="Hello world!"')
# lil2_js = LaboratoryInLanguage(laboratory=lab, language=js, test_case=tc, code='text="Hello world!"')
# lil2_cpp = LaboratoryInLanguage(laboratory=lab, language=cpp, test_case=tc, code='string text="Hello world!";')
# lil2_python.save()
# lil2_js.save()
# lil2_cpp.save()

labs/forms.py
from django import forms

from .models import Laboratory, Subject, Language, TestCase, LaboratoryInLanguage


class LaboratoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subject'].empty_label = "Subject is not selected"

    class Meta:
        model = Laboratory
        fields = ['title', 'description', 'pub_date', 'subject']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'description': forms.Textarea(attrs={'cols': 60, 'rows': 20})
        }


# class TestCaseForm(forms.ModelForm):
#     class Meta:
#         model = TestCase
#
#     fields = ['description', 'description_input', 'description_output', 'expected_output']
#     widgets = {
#         'description': forms.Textarea(attrs={'cols': 60, 'rows': 20})
#     }
#
#
# class LaboratoryInLanguageForm(forms.ModelForm):
#     class Meta:
#         model = LaboratoryInLanguage
#
#     fields = ['code']
######
    # laboratory = models.ForeignKey(
    #     Laboratory, on_delete=models.CASCADE
    # )  # 1 laboratory -> * laboratory in language
    # language = models.ForeignKey(
    #     Language, on_delete=models.CASCADE
    # )  # 1 language -> * laboratory in language
    # test_case = models.ForeignKey(
    #     TestCase, on_delete=models.CASCADE
    # )  # 1 test_case -> * laboratory in language
    #
    # code = models.CharField(max_length=200)  # code that runs before user code

labs/views.py
import asyncio
import datetime
import logging

from asgiref.sync import sync_to_async
from django.http import Http404
from django.shortcuts import get_object_or_404, render
import piston_rspy

from .models import Laboratory, Language, LaboratoryInLanguage, TestCase
from .forms import LaboratoryForm

def show_lab(request):
    pass
def new_lab(request):
    if request.method != 'POST':
        # порожня форма
        form = LaboratoryForm()
    else:
        form = LaboratoryForm(data=request.POST)
        if form.is_valid():
            form.save()

    # Показати порожню форму
    context = {'form': form}
    return render(request, 'new_lab.html', context)


def index(request):
    latest_labs_list = Laboratory.objects.all()
    context = {'latest_labs_list': latest_labs_list}
    return render(request, 'index.html', context)


async def detail(request, laboratory_id):
    laboratory = await get_laboratory(laboratory_id)
    test_cases = await get_laboratory_test_cases(laboratory)
    lab_in_languages = await get_laboratory_available_languages(laboratory)
    languages = await get_languages(lab_in_languages)

    if request.method == 'GET':
        test_cases_result = []
        for test_case in test_cases:
            result = (test_case, None)
            test_cases_result.append(result)
        return render(
            request,
            'detail.html',
            {
                'laboratory': laboratory,
                'test_cases': test_cases,
                'languages': languages,
                'test_cases_result': test_cases_result,
            },
        )
    else:
        return await send(request, laboratory, test_cases, lab_in_languages, languages)


@sync_to_async
def get_laboratory(laboratory_id: int) -> Laboratory:
    return get_object_or_404(Laboratory, pk=laboratory_id)


@sync_to_async
def get_laboratory_test_cases(laboratory: Laboratory) -> list[TestCase]:
    return list(laboratory.testcase_set.all())


@sync_to_async
def get_laboratory_test_cases(laboratory: Laboratory) -> list[TestCase]:
    return list(laboratory.testcase_set.all())


@sync_to_async
def get_laboratory_available_languages(laboratory: Laboratory) -> list[LaboratoryInLanguage]:
    return list(laboratory.laboratoryinlanguage_set.all())


@sync_to_async
def get_languages(
        laboratory_available_languages: list[LaboratoryInLanguage],
) -> list[Language]:
    return list({lil.language for lil in laboratory_available_languages})


@sync_to_async
def get_language_from_laboratory_languages(
        lab_in_languages: list[LaboratoryInLanguage], language_title: str
) -> tuple[list[LaboratoryInLanguage], Language]:
    lab_in_languages = [
        lil for lil in lab_in_languages if lil.language.title == language_title
    ]
    if len(lab_in_languages) == 0:
        raise Http404('Language cannot be empty.')

    language = lab_in_languages[0].language  # any
    return lab_in_languages, language


async def send(request, laboratory, test_cases, lab_in_languages, languages):
    user_code = request.POST.get('code', None)
    if user_code is None:
        raise Http404('User code cannot be empty.')

    language_title = request.POST.get('language', None)
    if language_title is None:
        raise Http404('Code language cannot be empty.')

    labs_in_languages, language = await get_language_from_laboratory_languages(
        lab_in_languages, language_title
    )

    input_coroutines = []
    for i, lab_in_language in enumerate(labs_in_languages):
        file_content = f'{lab_in_language.code}\n\n{user_code}'
        input_coroutines.append(get_file_output(i, file_content, language))

    start = datetime.datetime.now()
    system_cases = await asyncio.gather(*input_coroutines, return_exceptions=True)
    end = start - datetime.datetime.now()
    logging.info(f'Test finished in {end}ms')

    test_cases_result = []
    for test_case, system_output in zip(test_cases, system_cases):
        result = (test_case, test_case.expected_output == system_output)
        test_cases_result.append(result)

    return render(
        request,
        'detail.html',
        {
            'laboratory': laboratory,
            'test_cases': test_cases,
            'test_cases_result': test_cases_result,
            'languages': languages,
            'lab_in_languages': lab_in_languages,
            'user_code': user_code,
            'language_title': language_title,
        },
    )


async def get_file_output(time, file_content: str, language: Language):
    await asyncio.sleep(0.3 * time)
    if language.title == 'cpp':
        file_content = (
            '#include <iostream>\n'
            'using namespace std;\n'
            'int main() {\n'
            f'{file_content}\n'
            'return 0;}'
        )

    client = piston_rspy.Client()
    response = await client.execute(
        piston_rspy.Executor()
        .set_language(language.title)
        .add_file(piston_rspy.File(name='main', content=file_content, ))
    )

    user_output = response.run.output.removesuffix('\n')
    logging.info(f'Language: {response.language} v{response.version}')

    if response.compile:
        logging.info(f'Compilation:\n{response.compile.output}')
    logging.info(f'Output: "{user_output}"')
    return user_output

labs/templates/detail.html
{% extends "template.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'styles/detail.css' %}">
{% endblock %}


{% block content %}
<h1 class="page-title">{{ laboratory.title }}</h1>
<p class="lab-description">{{ laboratory.description }}</p>
<div class="lab-info-container">
    <div class="lab-info">
        <div class="test-cases">
            <h4>Test-cases:</h4>
            {% for test_case, result in test_cases_result %}
            <div class="test-case-info 
            {% if result == True %} test-case-passed {% endif %}
            {% if result == False %} test-case-failed {% endif %}">
                <div class="test-case-info__description">
                    <!-- TODO refactor "if endif" approach-->
                    {% if result == None %}
                        <img class="test-case-info__icon" src="{% static '/images/neutral-icon.png' %}" alt="Test icon">
                    {% endif %}
                    {% if result %}
                        <img class="test-case-info__icon" src="{% static '/images/tick-icon.png' %}" alt="Tick icon">
                    {% endif %}
                    {% if result == False %}
                        <img class="test-case-info__icon" src="{% static '/images/cross-icon.png' %}" alt="Cross icon">
                    {% endif %}
                    <p>{{ test_case.description }}</p>
                </div>
                <div class="test-case-info__data">
                    <p><b>Input:</b> {{ test_case.description_input }}</p>|
                    <p><b>Output:</b> {{ test_case.description_output }}</p>
                </div>

            </div>
            {% endfor %}
        </div>
    </div>

    <form id="code-form" action="{% url 'send' laboratory.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ laboratory.title }}</h1>
            </legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <div class="language-select">
                <!-- TODO beautify select -->
                <select name="language">
                    {% for language in languages %}
                        {% if language_title == language.title %}
                            <option value={{ language.title }} selected>{{ language.description }}</option>
                        {% else %}
                            <option value={{ language.title }}>{{ language.description }}</option>
                        {% endif %}
                    {% endfor %}

                </select>
            </div>
            <textarea placeholder="Type your code here" id="code" name="code" cols="40" rows="20">{% if user_code %}{{ user_code }}{% endif %}</textarea>
        </fieldset>
        <input class="submit-btn" type="submit" value="Send">
    </form>
</div>
<script>
    const form = document.getElementById('code-form');
    const bodyClasses = document.body.classList;
    form.addEventListener('submit', (e) => {
        // e.preventDefault();
        bodyClasses.add('is-loading');
    })
    setTimeout(() => bodyClasses.remove('is-loading'), 5000)
</script>
{% endblock %}

labs/templates/index.html
{% extends "template.html" %}
{% load static %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/index.css' %}"> 
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.student %}
            <p>STUDENT</p>
            {% if latest_labs_list %}
                <h1 class="page-title">Here you can see list of available labs</h1>
                <ol class="labs-list">
                {% for laboratory in latest_labs_list %}
                    <a class="labs-list__item" href="{% url 'labs:detail' laboratory.id %}">
                        <li>{{ laboratory.title }}</li>
                    </a>
                {% endfor %}
                </ol>
            {% else %}
                <p class="no-labs-template">No labs are available.</p>
            {% endif %}
        {% else %}
            <p>TEACHER</p>

        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="/logout">Logout</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Welcome, {{user.username}}</a>
        </li>

    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
        </li>
    {% endif %}
{% endblock %}

labs/templates/navbar.html
 <!--Navbar-->
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container my-0 mx-auto">
    <a class="navbar-brand h2" href="#">Easy Lab</a>
    <p class="nav-item w-75 text-center">You are logged in as {% if user.student %} STUDENT {% else %} TEACHER {% endif %}</p>

    <div class="collapse navbar-collapse justify-content-end align-items-center" id="navbarText">
      <ul class="navbar-nav mr-auto">

        {% if user.is_authenticated %}

        <li>
          <p class="nav-link" href="#">Welcome, {{user.username}}</p>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

labs/templates/new_lab.html
{% extends "template.html" %}
{% load static %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/index.css' %}">
{% endblock %}

{% block content %}
<!--    {% if user.is_authenticated %}-->
            <p>TEACHER</p>
            <h1 class="page-title">Here you can add labs</h1>
            <form action="{% url 'labs:new_lab' %}" method='post'>
                {% csrf_token %}
                {{ form.as_p }}
                <button name="submit">Add Lab</button>
            </form>
<!--    {% endif %}-->
{% endblock %}

labs/templates/send.html
<h1>{{ laboratory.title }}</h1>
<ul>
{% for test_name, test_result in result.items %}
    <li>{{ test_name }} status: {{ test_result }}</li>
{% endfor %}
</ul>
<br>
<a href="{% url 'detail' laboratory.id %}">Back to {{ laboratory.title }}</a>

labs/templates/template.html
{% load static %}
{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}

{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="stylesheet" href="{% static 'styles/general-styles.css' %}">
  {% block styles %}<!-- insert stylesheet here -->{% endblock %}
  <title>Easy Lab</title>
</head>

<body>
  <div class="loader"></div>
   <!--Navbar-->
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container my-0 mx-auto">
    <a class="navbar-brand h2" href="#">Easy Lab</a>
    {% if user.is_authenticated %}
    <p class="nav-item w-75 text-center">You are logged in as {% if user.student %} STUDENT {% else %} TEACHER {% endif %}</p>
    {% endif %}
    <div class="collapse navbar-collapse justify-content-end align-items-center" id="navbarText">
      <ul class="navbar-nav mr-auto">

        {% if user.is_authenticated %}

        <li>
          <p class="nav-link" href="#">Welcome, {{user.username}}</p>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>
  <div class="container">
    {% block content %}<!-- insert content here -->{% endblock %}
  </div>
</body>

</html>